/**
 * Advanced integration tests — complex, realistic scenarios.
 * Uses fixtures generated by scripts/generate_advanced_fixtures.py
 * with hardcoded expected values (no Parselmouth dependency).
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { analyzeAudio } from '../../src/audio/analyzer';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function loadWav(relPath: string): { samples: Float32Array; sampleRate: number } {
  const buf = readFileSync(resolve(__dirname, '../../', relPath));
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  let offset = 12;
  let sampleRate = 44100;
  let dataOffset = 0;
  let dataSize = 0;
  while (offset < buf.length - 8) {
    const chunkId = String.fromCharCode(buf[offset], buf[offset + 1], buf[offset + 2], buf[offset + 3]);
    const chunkSize = view.getUint32(offset + 4, true);
    if (chunkId === 'fmt ') sampleRate = view.getUint32(offset + 12, true);
    else if (chunkId === 'data') { dataOffset = offset + 8; dataSize = chunkSize; break; }
    offset += 8 + chunkSize;
  }
  const numSamples = dataSize / 2;
  const samples = new Float32Array(numSamples);
  for (let i = 0; i < numSamples; i++) {
    samples[i] = view.getInt16(dataOffset + i * 2, true) / 32768;
  }
  return { samples, sampleRate };
}

function loadJson(relPath: string) {
  return JSON.parse(readFileSync(resolve(__dirname, '../../', relPath), 'utf-8'));
}

/** Pearson correlation coefficient. */
function correlation(a: number[], b: number[]): number {
  const n = Math.min(a.length, b.length);
  if (n < 3) return 0;
  const meanA = a.slice(0, n).reduce((s, v) => s + v, 0) / n;
  const meanB = b.slice(0, n).reduce((s, v) => s + v, 0) / n;
  let num = 0, denA = 0, denB = 0;
  for (let i = 0; i < n; i++) {
    const da = a[i] - meanA, db = b[i] - meanB;
    num += da * db; denA += da * da; denB += db * db;
  }
  const den = Math.sqrt(denA * denB);
  return den === 0 ? 0 : num / den;
}

// ─── 1. Vowel Sequence (/a/ → /i/ → /u/ → /e/ → /o/) ───────────────────────

describe('Advanced — vowel sequence formant tracking', () => {
  const { samples, sampleRate } = loadWav('fixtures/vowel_sequence.wav');
  const result = analyzeAudio(samples, sampleRate);
  const expected = loadJson('fixtures/vowel_sequence_expected.json');

  it('detects pitch at ~120 Hz throughout', () => {
    const voiced = result.pitch.frequencies.filter((f): f is number => f !== null && f > 0);
    expect(voiced.length).toBeGreaterThan(10);
    const meanPitch = voiced.reduce((s, v) => s + v, 0) / voiced.length;
    expect(Math.abs(meanPitch - 120)).toBeLessThan(5);
  });

  it('F1 differs between vowels (tracking works)', () => {
    // Check that F1 in /a/ segment (high F1~700) differs from /i/ segment (low F1~270)
    const times = result.formants?.times ?? [];
    const f1 = result.formants?.f1 ?? [];

    // Get F1 values in /a/ segment (0.05-0.25s) and /i/ segment (0.35-0.55s)
    const f1_a: number[] = [];
    const f1_i: number[] = [];
    for (let i = 0; i < times.length; i++) {
      const t = times[i];
      const v = f1[i];
      if (v === null || v === undefined) continue;
      if (t >= 0.05 && t <= 0.25) f1_a.push(v);
      if (t >= 0.35 && t <= 0.55) f1_i.push(v);
    }

    if (f1_a.length > 0 && f1_i.length > 0) {
      const meanF1_a = f1_a.reduce((s, v) => s + v, 0) / f1_a.length;
      const meanF1_i = f1_i.reduce((s, v) => s + v, 0) / f1_i.length;
      // /a/ should have higher F1 than /i/
      expect(meanF1_a).toBeGreaterThan(meanF1_i);
    }
  });

  it('total duration is ~1.5s', () => {
    expect(result.duration).toBeCloseTo(1.5, 1);
  });
});

// ─── 2. Noisy Vowel ─────────────────────────────────────────────────────────

describe('Advanced — noisy vowel (SNR 10dB)', () => {
  const { samples, sampleRate } = loadWav('fixtures/noisy_vowel.wav');
  const result = analyzeAudio(samples, sampleRate);
  const expected = loadJson('fixtures/noisy_vowel_expected.json');

  it('pitch still detectable at ~120 Hz despite noise', () => {
    const voiced = result.pitch.frequencies.filter((f): f is number => f !== null && f > 0);
    // At least some frames should detect pitch
    expect(voiced.length).toBeGreaterThan(5);
    const meanPitch = voiced.reduce((s, v) => s + v, 0) / voiced.length;
    // Allow wider tolerance due to noise
    expect(Math.abs(meanPitch - expected.f0)).toBeLessThan(10);
  });

  it('HNR is approximately 10 dB (±3 dB)', () => {
    const hnr = result.harmonicity.meanHnrDb;
    expect(hnr).toBeGreaterThan(expected.expected_hnr_db - expected.hnr_tolerance_db);
    expect(hnr).toBeLessThan(expected.expected_hnr_db + expected.hnr_tolerance_db);
  });
});

// ─── 3. Pitch Contour (80 → 200 Hz) ─────────────────────────────────────────

describe('Advanced — rising pitch contour', () => {
  const { samples, sampleRate } = loadWav('fixtures/pitch_contour.wav');
  const result = analyzeAudio(samples, sampleRate);
  const expected = loadJson('fixtures/pitch_contour_expected.json');

  it('pitch contour is monotonically rising', () => {
    const voiced = result.pitch.frequencies.filter((f): f is number => f !== null && f > 0);
    expect(voiced.length).toBeGreaterThan(10);
    // Check overall trend: last quarter mean > first quarter mean
    const q = Math.floor(voiced.length / 4);
    const firstQ = voiced.slice(0, q).reduce((s, v) => s + v, 0) / q;
    const lastQ = voiced.slice(-q).reduce((s, v) => s + v, 0) / q;
    expect(lastQ).toBeGreaterThan(firstQ);
  });

  it('pitch contour shape correlation > 0.9 with expected linear ramp', () => {
    // Build aligned arrays
    const ourPitches: number[] = [];
    const expectedPitches: number[] = [];

    for (let i = 0; i < result.pitch.times.length; i++) {
      const t = result.pitch.times[i];
      const f = result.pitch.frequencies[i];
      if (f === null || t < 0.05 || t > 0.95) continue;
      ourPitches.push(f);
      // Expected: linear from 80 to 200
      expectedPitches.push(80 + 120 * t);
    }

    if (ourPitches.length > 5) {
      const corr = correlation(ourPitches, expectedPitches);
      expect(corr).toBeGreaterThan(0.9);
    }
  });

  it('pitch range spans from ~80 to ~200 Hz', () => {
    const voiced = result.pitch.frequencies.filter((f): f is number => f !== null && f > 0);
    const minP = Math.min(...voiced);
    const maxP = Math.max(...voiced);
    expect(minP).toBeLessThan(100);
    expect(maxP).toBeGreaterThan(180);
  });
});

// ─── 4. Speech + Silence alternating ─────────────────────────────────────────

describe('Advanced — speech/silence voicing detection', () => {
  const { samples, sampleRate } = loadWav('fixtures/speech_silence.wav');
  const result = analyzeAudio(samples, sampleRate);
  const expected = loadJson('fixtures/speech_silence_expected.json');

  it('silence segments have null/unvoiced pitch', () => {
    const silenceSegs = expected.segments.filter((s: any) => s.type === 'silence');
    let silenceFrames = 0;
    let unvoicedFrames = 0;

    for (let i = 0; i < result.pitch.times.length; i++) {
      const t = result.pitch.times[i];
      const inSilence = silenceSegs.some((s: any) => t >= s.start + 0.02 && t <= s.end - 0.02);
      if (!inSilence) continue;
      silenceFrames++;
      if (result.pitch.frequencies[i] === null || result.pitch.frequencies[i] === 0) {
        unvoicedFrames++;
      }
    }

    if (silenceFrames > 0) {
      const accuracy = unvoicedFrames / silenceFrames;
      expect(accuracy).toBeGreaterThan(0.8); // ≥80% of silence frames should be unvoiced
    }
  });

  it('voiced segments have detected pitch at ~120 Hz', () => {
    const voicedSegs = expected.segments.filter((s: any) => s.type === 'voiced');
    const pitchesInVoiced: number[] = [];

    for (let i = 0; i < result.pitch.times.length; i++) {
      const t = result.pitch.times[i];
      const f = result.pitch.frequencies[i];
      const inVoiced = voicedSegs.some((s: any) => t >= s.start + 0.05 && t <= s.end - 0.05);
      if (inVoiced && f !== null && f > 0) {
        pitchesInVoiced.push(f);
      }
    }

    expect(pitchesInVoiced.length).toBeGreaterThan(5);
    const mean = pitchesInVoiced.reduce((s, v) => s + v, 0) / pitchesInVoiced.length;
    expect(Math.abs(mean - 120)).toBeLessThan(5);
  });

  it('intensity in silence is much lower than in voiced', () => {
    const silenceSegs = expected.segments.filter((s: any) => s.type === 'silence');
    const voicedSegs = expected.segments.filter((s: any) => s.type === 'voiced');

    const getIntensityInRange = (start: number, end: number) => {
      const vals: number[] = [];
      for (let i = 0; i < result.intensity.times.length; i++) {
        const t = result.intensity.times[i];
        if (t >= start + 0.02 && t <= end - 0.02) vals.push(result.intensity.values[i]);
      }
      return vals;
    };

    const silenceInt = silenceSegs.flatMap((s: any) => getIntensityInRange(s.start, s.end));
    const voicedInt = voicedSegs.flatMap((s: any) => getIntensityInRange(s.start, s.end));

    if (silenceInt.length > 0 && voicedInt.length > 0) {
      const meanSilence = silenceInt.reduce((s, v) => s + v, 0) / silenceInt.length;
      const meanVoiced = voicedInt.reduce((s, v) => s + v, 0) / voicedInt.length;
      // Voiced should be at least 20 dB louder than silence
      expect(meanVoiced - meanSilence).toBeGreaterThan(20);
    }
  });
});

// ─── 5. Jitter/Shimmer ──────────────────────────────────────────────────────

describe('Advanced — jitter and shimmer measurement', () => {
  const { samples, sampleRate } = loadWav('fixtures/jittery_voice.wav');
  const result = analyzeAudio(samples, sampleRate);
  const expected = loadJson('fixtures/jittery_voice_expected.json');

  it('detects pitch at ~440 Hz', () => {
    const voiced = result.pitch.frequencies.filter((f): f is number => f !== null && f > 0);
    expect(voiced.length).toBeGreaterThan(5);
    const meanPitch = voiced.reduce((s, v) => s + v, 0) / voiced.length;
    expect(Math.abs(meanPitch - expected.f0)).toBeLessThan(5);
  });

  it('jitter is positive and in reasonable range for perturbed signal', () => {
    const ourJitter = result.voiceQuality.jitterLocalPercent;
    // Synthesized with ~2% nominal jitter; algorithm may measure differently
    // but should be positive and < 5%
    expect(ourJitter).toBeGreaterThan(0.5);
    expect(ourJitter).toBeLessThan(5);
  });

  it('shimmer is positive and in reasonable range for perturbed signal', () => {
    const ourShimmer = result.voiceQuality.shimmerLocalPercent;
    // Synthesized with ~5% nominal shimmer; algorithm may measure differently
    // but should be positive and < 10%
    expect(ourShimmer).toBeGreaterThan(0.3);
    expect(ourShimmer).toBeLessThan(10);
  });
});

// ─── 6. Formant Bandwidth ────────────────────────────────────────────────────

describe('Advanced — formant bandwidth estimation', () => {
  const { samples, sampleRate } = loadWav('fixtures/vowel_bandwidth.wav');
  const result = analyzeAudio(samples, sampleRate);
  const expected = loadJson('fixtures/vowel_bandwidth_expected.json');

  it('detects F1 at ~700 Hz in both segments', () => {
    const times = result.formants?.times ?? [];
    const f1 = result.formants?.f1 ?? [];

    // Narrow segment (0.05-0.45)
    const f1_narrow: number[] = [];
    // Wide segment (0.55-0.95)
    const f1_wide: number[] = [];

    for (let i = 0; i < times.length; i++) {
      const v = f1[i];
      if (v === null || v === undefined) continue;
      if (times[i] >= 0.05 && times[i] <= 0.45) f1_narrow.push(v);
      if (times[i] >= 0.55 && times[i] <= 0.95) f1_wide.push(v);
    }

    if (f1_narrow.length > 0) {
      const mean = f1_narrow.reduce((s, v) => s + v, 0) / f1_narrow.length;
      // F1 should be in the ballpark of 700 Hz (±200 Hz given LPC variability)
      expect(mean).toBeGreaterThan(400);
      expect(mean).toBeLessThan(1000);
    }

    if (f1_wide.length > 0) {
      const mean = f1_wide.reduce((s, v) => s + v, 0) / f1_wide.length;
      expect(mean).toBeGreaterThan(400);
      expect(mean).toBeLessThan(1000);
    }
  });

  it('formant frequencies are consistent between narrow and wide segments', () => {
    // Both segments have same formant centers (700, 1200, 2600),
    // only bandwidth differs. F1 should be similar.
    const times = result.formants?.times ?? [];
    const f1 = result.formants?.f1 ?? [];

    const getF1Mean = (start: number, end: number) => {
      const vals: number[] = [];
      for (let i = 0; i < times.length; i++) {
        const v = f1[i];
        if (v === null || v === undefined) continue;
        if (times[i] >= start && times[i] <= end) vals.push(v);
      }
      return vals.length > 0 ? vals.reduce((s, v) => s + v, 0) / vals.length : null;
    };

    const narrowF1 = getF1Mean(0.05, 0.45);
    const wideF1 = getF1Mean(0.55, 0.95);

    if (narrowF1 !== null && wideF1 !== null) {
      // Should be within 200 Hz of each other (same formant center)
      expect(Math.abs(narrowF1 - wideF1)).toBeLessThan(200);
    }
  });
});
