/**
 * Cross-validation: compare web-praat output vs Praat (Parselmouth) reference.
 *
 * Reference data generated by tests/validation/generate-reference.py
 * using Parselmouth (Praat's C engine wrapped in Python).
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';
import { computePitch, computeFormants, computeIntensity } from '../../src/audio/analyzer';

const refPath = join(__dirname, 'reference', 'praat-reference.json');
const reference = JSON.parse(readFileSync(refPath, 'utf-8'));

// ─── Signal generators (must match Python exactly) ──────────────────────────────

function voiceLike(f0: number, duration: number, sr: number): Float32Array {
  const n = Math.round(duration * sr);
  const samples = new Float32Array(n);
  for (let h = 1; h <= 6; h++) {
    const amp = 0.8 / h;
    const freq = f0 * h;
    if (freq > sr / 2) break;
    for (let i = 0; i < n; i++) {
      samples[i] += amp * Math.sin(2 * Math.PI * freq * i / sr);
    }
  }
  return samples;
}

function sineWave(freq: number, duration: number, sr: number, amplitude = 0.8): Float32Array {
  const n = Math.round(duration * sr);
  const samples = new Float32Array(n);
  for (let i = 0; i < n; i++) {
    samples[i] = amplitude * Math.sin(2 * Math.PI * freq * i / sr);
  }
  return samples;
}

function resonator(input: Float32Array, freq: number, bw: number, sr: number): Float32Array {
  const output = new Float32Array(input.length);
  const omega = 2 * Math.PI * freq / sr;
  const r = Math.exp(-Math.PI * bw / sr);
  const a1 = -2 * r * Math.cos(omega);
  const a2 = r * r;
  let y1 = 0, y2 = 0;
  for (let i = 0; i < input.length; i++) {
    const y = input[i] - a1 * y1 - a2 * y2;
    output[i] = y;
    y2 = y1;
    y1 = y;
  }
  return output;
}

function formantSignal(f0: number, formants: number[], duration: number, sr: number): Float32Array {
  const n = Math.round(duration * sr);
  const period = Math.round(sr / f0);
  const impulse = new Float32Array(n);
  for (let i = 0; i < n; i += period) impulse[i] = 1.0;
  let signal = impulse;
  for (const freq of formants) signal = resonator(signal, freq, 80, sr);
  let max = 0;
  for (let i = 0; i < signal.length; i++) max = Math.max(max, Math.abs(signal[i]));
  if (max > 0) for (let i = 0; i < signal.length; i++) signal[i] /= max;
  return signal;
}

// ─── Pitch cross-validation ─────────────────────────────────────────────────────

describe('Cross-validation: Pitch vs Praat', () => {
  const pitchCases = Object.entries(reference).filter(([k]) => k.startsWith('pitch_'));

  for (const [key, ref] of pitchCases) {
    const { params, praat_mean_f0 } = ref as { params: { f0: number; duration: number; sr: number }; praat_mean_f0: number };
    if (!praat_mean_f0) continue;

    it(`${key}: web-praat vs Praat (target ${params.f0} Hz, Praat=${praat_mean_f0} Hz)`, () => {
      const signal = voiceLike(params.f0, params.duration, params.sr);
      const pitch = computePitch(signal, params.sr);
      const voiced = pitch.frequencies.filter((f): f is number => f !== null && f > 0);
      expect(voiced.length).toBeGreaterThan(5);
      const meanF0 = voiced.reduce((a, b) => a + b, 0) / voiced.length;

      // Must be within ±5 Hz of Praat's output
      const diff = Math.abs(meanF0 - praat_mean_f0);
      expect(diff).toBeLessThan(5);
    });
  }
});

// ─── Formant cross-validation ───────────────────────────────────────────────────

describe('Cross-validation: Formants vs Praat', () => {
  const formantCases = Object.entries(reference).filter(([k]) => k.startsWith('formant_'));

  for (const [key, ref] of formantCases) {
    const { params, praat_median_f1, praat_median_f2 } = ref as {
      params: { f0: number; formants: number[] };
      praat_median_f1: number | null;
      praat_median_f2: number | null;
    };

    it(`${key}: web-praat F1/F2 vs Praat (Praat F1=${praat_median_f1}, F2=${praat_median_f2})`, () => {
      const signal = formantSignal(params.f0, params.formants, 0.3, 16000);
      const formants = computeFormants(signal, 16000);
      const f1Values = formants.tracked[0]?.filter((f): f is number => f !== null && f > 0) ?? [];
      const f2Values = formants.tracked[1]?.filter((f): f is number => f !== null && f > 0) ?? [];

      if (praat_median_f1 && f1Values.length > 3) {
        const sorted = [...f1Values].sort((a, b) => a - b);
        const medianF1 = sorted[Math.floor(sorted.length / 2)];
        // Within ±150 Hz of Praat
        expect(Math.abs(medianF1 - praat_median_f1)).toBeLessThan(150);
      }

      if (praat_median_f2 && f2Values.length > 3) {
        const sorted = [...f2Values].sort((a, b) => a - b);
        const medianF2 = sorted[Math.floor(sorted.length / 2)];
        // Within ±350 Hz of Praat (F2 more variable due to LPC order sensitivity)
        expect(Math.abs(medianF2 - praat_median_f2)).toBeLessThan(350);
      }
    });
  }
});

// ─── Intensity cross-validation ─────────────────────────────────────────────────

describe('Cross-validation: Intensity vs Praat', () => {
  const intCases = Object.entries(reference).filter(([k]) => k.startsWith('intensity_'));

  // Check relative dB differences match Praat's
  it('amplitude doublings produce ~6 dB increase (matching Praat)', () => {
    const refs = intCases.map(([, r]) => r as { params: { amplitude: number }; praat_mean_intensity: number });
    for (let i = 1; i < refs.length; i++) {
      const praatDiff = refs[i].praat_mean_intensity - refs[i - 1].praat_mean_intensity;
      const signal1 = sineWave(200, 0.3, 16000, refs[i - 1].params.amplitude);
      const signal2 = sineWave(200, 0.3, 16000, refs[i].params.amplitude);
      const int1 = computeIntensity(signal1, 16000);
      const int2 = computeIntensity(signal2, 16000);
      const mean1 = int1.values.reduce((a, b) => a + b, 0) / int1.values.length;
      const mean2 = int2.values.reduce((a, b) => a + b, 0) / int2.values.length;
      const ourDiff = mean2 - mean1;
      // Our dB difference should match Praat's within ±2 dB
      expect(Math.abs(ourDiff - praatDiff)).toBeLessThan(2);
    }
  });
});
